config/routes.rb
Rails.application.routes.draw do
  resources :game_configs
  resources :workouts
  resources :weights
  resources :exercises
  resources :bodyparts
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root 'workouts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  belongs_to :exercise
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_workout, only: [:show, :edit, :update, :destroy]


  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.where(user_id: current_user.id).reverse_order
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new(user_id: current_user)
    @exercises = Exercise.all
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout_temp = Workout.new(workout_params)
    @workout_temp.user_id = current_user.id
    @workout_lookups = Workout.where("created_at >= ? and user_id = ? and exercise_id = ?", DateTime.now - 1.minutes, @workout_temp.user_id, @workout_temp.exercise_id)
    if @workout_lookups.empty?
      @workout = @workout_temp
    else
      @workout_lookup = @workout_lookups.first
      @workout_lookup.reps = @workout_lookup.reps + @workout_temp.reps
      @workout = @workout_lookup
    end
    respond_to do |format|
      if @workout.save
        #update the player stats
        @workout.exercise.bodyparts.each do |bodypart|
          tmpstat = current_user.user_stats.where('bodypart_id = ?', bodypart.id).first
          tmpstat.base_points = tmpstat.base_points + @workout_temp.reps
          tmpstat.level_points = Math.sqrt(tmpstat.base_points).round(1)
          tmpstat.save
        end
        format.html { redirect_to new_workout_path, notice: 'Added ' + @workout.exercise.name + ' +' + @workout.reps.to_s }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:exercise_id, :reps)
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Exercise</th>
      <th>Reps</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% form_count = 1 %>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.name %></td>
        <%= simple_form_for @workout, html: { :id => 'workout_form_' + form_count.to_s } do |f| %>
        	<%= f.hidden_field :exercise_id, value: exercise.id.to_s %>
          <%= f.hidden_field :reps, value: '1' %>
        	<td><%= f.button :submit, '+1' %></td>
          <% form_count += 1 %>
        <% end %>
        <%= simple_form_for @workout, html: { :id => 'workout_form_' + form_count.to_s } do |f| %>
        	<%= f.hidden_field :exercise_id, value: exercise.id.to_s %>
          <%= f.hidden_field :reps, value: '5' %>
        	<td><%= f.button :submit, '+5' %></td>
          <% form_count += 1 %>
        <% end %>
        <%= simple_form_for @workout, html: { :id => 'workout_form_' + form_count.to_s } do |f| %>
        	<%= f.hidden_field :exercise_id, value: exercise.id.to_s %>
          <%= f.hidden_field :reps, value: '10' %>
        	<td><%= f.button :submit, '+10' %></td>
          <% form_count += 1 %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<div class="row">
  <div class="col-xs-8"><h1>Workouts</h1></div>
  <div class="col-xs-4 centered">
    <br>
    <%= button_to 'New Workout', new_workout_path, :method => "get", :class => 'btn btn-default' %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>DateTime</th>
      <th>Exercise</th>
      <th>Reps</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= workout.exercise.name %></td>
        <td><%= workout.reps %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @workout.user %>
</p>

<p>
  <strong>Exercise:</strong>
  <%= @workout.exercise %>
</p>

<p>
  <strong>Reps:</strong>
  <%= @workout.reps %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>