config/routes.rb
Rails.application.routes.draw do
  resources :game_configs
  resources :workouts
  resources :weights
  resources :exercises
  resources :bodyparts
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root 'workouts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game_config.rb
class GameConfig < ApplicationRecord
end

app/controllers/game_configs_controller.rb
class GameConfigsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game_config, only: [:show, :edit, :update, :destroy]

  # GET /game_configs
  # GET /game_configs.json
  def index
    @game_configs = GameConfig.all
  end

  # GET /game_configs/1
  # GET /game_configs/1.json
  def show
  end

  # GET /game_configs/new
  def new
    @game_config = GameConfig.new
  end

  # GET /game_configs/1/edit
  def edit
  end

  # POST /game_configs
  # POST /game_configs.json
  def create
    @game_config = GameConfig.new(game_config_params)

    respond_to do |format|
      if @game_config.save
        format.html { redirect_to @game_config, notice: 'Game config was successfully created.' }
        format.json { render :show, status: :created, location: @game_config }
      else
        format.html { render :new }
        format.json { render json: @game_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_configs/1
  # PATCH/PUT /game_configs/1.json
  def update
    respond_to do |format|
      if @game_config.update(game_config_params)
        format.html { redirect_to @game_config, notice: 'Game config was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_config }
      else
        format.html { render :edit }
        format.json { render json: @game_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_configs/1
  # DELETE /game_configs/1.json
  def destroy
    @game_config.destroy
    respond_to do |format|
      format.html { redirect_to game_configs_url, notice: 'Game config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_config
      @game_config = GameConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_config_params
      params.require(:game_config).permit(:level_rate, :level_method, :decay_per_day)
    end
end

app/helpers/game_configs_helper.rb
module GameConfigsHelper
end

app/views/game_configs/_form.html.erb
<%= simple_form_for(@game_config) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :level_rate %>
    <%= f.input :level_method %>
    <%= f.input :decay_per_day %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/game_configs/edit.html.erb
<h1>Editing Game Config</h1>

<%= render 'form', game_config: @game_config %>

<%= link_to 'Show', @game_config %> |
<%= link_to 'Back', game_configs_path %>

app/views/game_configs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Game Configs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Level rate</th>
      <th>Level method</th>
      <th>Decay per day</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_configs.each do |game_config| %>
      <tr>
        <td><%= game_config.level_rate %></td>
        <td><%= game_config.level_method %></td>
        <td><%= game_config.decay_per_day %></td>
        <td><%= link_to 'Edit', edit_game_config_path(game_config) %></td>
        <td><%= link_to 'Destroy', game_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game Config', new_game_config_path %>

app/views/game_configs/new.html.erb
<h1>New Game Config</h1>

<%= render 'form', game_config: @game_config %>

<%= link_to 'Back', game_configs_path %>

app/views/game_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Level rate:</strong>
  <%= @game_config.level_rate %>
</p>

<p>
  <strong>Level method:</strong>
  <%= @game_config.level_method %>
</p>

<p>
  <strong>Decay per day:</strong>
  <%= @game_config.decay_per_day %>
</p>

<%= link_to 'Edit', edit_game_config_path(@game_config) %> |
<%= link_to 'Back', game_configs_path %>