config/routes.rb
Rails.application.routes.draw do
  resources :game_configs
  resources :workouts
  resources :weights
  resources :exercises
  resources :bodyparts
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root 'workouts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bodypart.rb
class Bodypart < ApplicationRecord
	has_and_belongs_to_many :exercises
	has_many :user_stats
end

app/controllers/bodyparts_controller.rb
class BodypartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bodypart, only: [:show, :edit, :update, :destroy]

  # GET /bodyparts
  # GET /bodyparts.json
  def index
    @bodyparts = Bodypart.all
  end

  # GET /bodyparts/1
  # GET /bodyparts/1.json
  def show
  end

  # GET /bodyparts/new
  def new
    @bodypart = Bodypart.new
  end

  # GET /bodyparts/1/edit
  def edit
  end

  # POST /bodyparts
  # POST /bodyparts.json
  def create
    @bodypart = Bodypart.new(bodypart_params)

    respond_to do |format|
      if @bodypart.save
        format.html { redirect_to bodyparts_path, notice: 'Bodypart was successfully created.' }
        format.json { render :show, status: :created, location: @bodypart }
      else
        format.html { render :new }
        format.json { render json: @bodypart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bodyparts/1
  # PATCH/PUT /bodyparts/1.json
  def update
    respond_to do |format|
      if @bodypart.update(bodypart_params)
        format.html { redirect_to bodyparts_path, notice: 'Bodypart was successfully updated.' }
        format.json { render :show, status: :ok, location: @bodypart }
      else
        format.html { render :edit }
        format.json { render json: @bodypart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bodyparts/1
  # DELETE /bodyparts/1.json
  def destroy
    @bodypart.destroy
    respond_to do |format|
      format.html { redirect_to bodyparts_url, notice: 'Bodypart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bodypart
      @bodypart = Bodypart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bodypart_params
      params.require(:bodypart).permit(:name)
    end
end

app/helpers/bodyparts_helper.rb
module BodypartsHelper
end

app/views/bodyparts/_form.html.erb
<%= simple_form_for bodypart do |f| %>
  <div class="row">
    <div class="col-sm-6 form-group"><%= f.input :name, :autofocus => true %></div>
  </div>
  <div class="row">
    <div class="actions">
      <div class="col-xs-6"><%= f.submit :class => 'btn btn-default' %></div>
    </div>
<% end %>
  <div class="col-sm-2 col-xs-6">
    <%= button_to 'Back', bodyparts_path, :method => "get", :class => 'btn btn-default' %>
  </div>
  </div>

app/views/bodyparts/edit.html.erb
<h1>Editing Bodypart</h1>

<%= render 'form', bodypart: @bodypart %>

app/views/bodyparts/index.html.erb
<div class="row">
  <div class="col-xs-8"><h1>Bodyparts</h1></div>
  <div class="col-xs-4 centered">
    <br>
    <%= button_to 'New Bodypart', new_bodypart_path, :method => "get", :class => 'btn btn-default' %>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @bodyparts.each do |bodypart| %>
      <tr>
        <td><%= bodypart.name %></td>
        <td>
          <%= button_to 'Edit', edit_bodypart_path(bodypart), :method => "get", :class => 'btn btn-default' %>
        </td>
        <td>
          <%= link_to 'Destroy', bodypart, method: :delete, :class => 'btn btn-default', data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Bodypart', new_bodypart_path, :method => "get", :class => 'btn btn-default' %>

app/views/bodyparts/new.html.erb
<h1>New Bodypart</h1>

<%= render 'form', bodypart: @bodypart %>

app/views/bodyparts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bodypart.name %>
</p>

<%= link_to 'Edit', edit_bodypart_path(@bodypart) %> |
<%= link_to 'Back', bodyparts_path %>